FunkinCrew/funkin.assets

- .gitattributes
Allows .hxc files to be identified as Haxe ~~and displayed with its formatting~~ on GitHub
> Add .gitattributes with linguist-language

- preload/data/ui/chart-editor/dialogs/user-guide.xml
Closes https://github.com/FunkinCrew/Funkin/issues/3697
Adds the Focus Camera and note context/options menu hotkeys that are currently not documented anywhere (except for the camera events in the changelog for v0.3.2).
If you have a better and/or shorter description to the hotkeys you're very welcome to suggest changes.
> Add missing hotkeys to User Guide

- preload/data/songs/monster/monster-metadata.json
The [_Friday Night Funkin'_ wiki](https://fridaynightfunkin.wiki.gg/wiki/Monster_(Song)#Trivia) says that MtH did the improved charting for the song when the Week 7 update released, but she isn't credited at the time of this writing, with only ChaoticGamerCG and Spazkid being credited.
> Fix MtH not being credited in Monster's metadata

- exclude/data/ui/chart-editor/components/playbar.xml
The chart editor's Skip Forward button is named "Skip Back"
> Fix "Skip Forward" button's name

- preload/scripts/characters/tankman.hxc
Says what it says it does. Tankman's ugh animation continues while other notes are hit, making it look strange, and it also just matches the last major update
before:
https://github.com/FunkinCrew/funkin.assets/assets/51544115/6b3cdd6b-136f-4664-bff2-586b006eb114
after:
https://github.com/FunkinCrew/funkin.assets/assets/51544115/4c5672bd-4d72-4b96-9429-66811d3ef31a
> Don't make tankmans ugh animation ignore other inputs

- preload/images/fonts/freeplay-clear.xml
Fixes https://github.com/FunkinCrew/Funkin/issues/2907
Adjusts boundaries and standardizes heights in freeplay-clear.xml to fix misaligned numbers.
This is the best alignment I can achieve without editing the font itself. 
Perfect alignment can be reached with tiny font edits!
https://github.com/FunkinCrew/funkin.assets/assets/170126004/d32d9053-db7c-4dca-ac30-da1f20245b3a
> Align freeplay clear percentage

- preload/shaders/InverseDots.frag
fixed grid logic (in turn fixing an implicit cast error) and made some optimizations
now it looks identical to Flash/Animate !!
in Animate for reference:
> fix + optimize InverseDots shader

- preload/data/songs/monster/monster-metadata.json
Part of an effort to recover 10 merged but lost PRs in funkin.assets
See https://github.com/FunkinCrew/funkin.assets/pull/66 for the original PR
> <PR Recovery> Fix MtH not being credited in Monster's metadata

- preload/scripts/characters/pico-playable.hxc
Please don't flood my console with messages of Pico's idle animation:
> Remove Trace Call for Pico's animations

- preload/scripts/characters/pico-playable.hxc
Fixes https://github.com/FunkinCrew/Funkin/issues/3545
[This commit](https://github.com/FunkinCrew/funkin.assets/commit/f6d758f5379fec730805e639f69dfff8000bec13) made it so that `burpSmile` and `burpSmileLong` would set `playerVolume` to 1 so that Pico's burps would always be heard.
This PR adds `burpShit` to the list of animations, ensuring that Pico can burp to his heart's content.
https://github.com/user-attachments/assets/2b2c0278-43a2-4f0b-8ead-b31e08c6d01a
> Ensure volume enables for burpShit animation as well

- preload/data/players/pico.json
Pico's `fistPump` animation offsets were weird, which made the transition to idle look awkward. This PR corrects the offsets for that animation.
https://github.com/user-attachments/assets/b5bca1f8-a51a-4055-875a-0cabf530c8dd
https://github.com/user-attachments/assets/f10824fc-3aef-45b7-a8a4-1cc260e5dc18
> [BUGFIX] Fix Pico's `fistPump` offsets

- preload/scripts/characters/bf.hxc
Fixes https://github.com/FunkinCrew/Funkin/issues/2554
The script would always suppose the current state's substate was the `GameOverSubState` which isn't the case when you're in the chart editor.
This changes it so it gets the game over substate directly from the singleton.
> [BUGFIX] Fix error when getting fakeout death while testing in Chart Editor

- preload/data/characters/pico-pixel.json
In the chart editor, when selecting Pico as his playable pixel variant, his name does not correspond with the other Pico variants.
In summary, this pull request makes the `pico-pixel` character have it’s name be consistent with the other Pico variants.
> [ENHANCEMENT]: Pico Pixel Character Name Fix

- preload/scripts/songs/darnell.hxc
Fixes https://github.com/FunkinCrew/Funkin/issues/4813
* Replaces instances of 'pico' with 'bf' in the function `listAltInstrumentalIds` in `darnell.hxc`
* This makes the game check if Darnell (BF Mix) is beaten, not Darnell (Pico Mix)
> Properly check for Darnell (BF Mix) alternate instrumental

- preload/scripts/characters/nene-christmas.hxc
- preload/scripts/characters/nene-dark.hxc
- preload/scripts/characters/nene-pixel.hxc
- preload/scripts/characters/nene.hxc
- preload/scripts/characters/otis-speaker.hxc
Fixes FunkinCrew/Funkin#4941
I'm not sure why the A-bot is reacting to the start of the song when it ends, but the easiest solution would be to just dump the sound when the song ends.
Videos of the visualizer not jumping in volume when the song ends:
https://github.com/user-attachments/assets/8a9c82e7-5c43-4a33-a0b4-644594612720
https://github.com/user-attachments/assets/4f8bcc50-e16a-44db-bd67-979612049d7f
https://github.com/user-attachments/assets/c47f1096-74a7-4a98-9a7d-0ba7981cb150
> [BUGFIX] Fix the A-bot visualizer jumping in volume when the song ends

- preload/scripts/songs/senpai.hxc
* As seen in https://github.com/FunkinCrew/Funkin/issues/4767 and https://github.com/FunkinCrew/Funkin/issues/4477, there is an issue that you are able to spam buttons (including the `RESET` key) before the dialogue starts, which bugs out the game. However, with this PR, with just two simple lines of code, this issue is fixed.
> [FIX] Fix Death Before Senpai Dialogue

- preload/scripts/characters/pico-blazin.hxc
N/A
Closes https://github.com/FunkinCrew/Funkin/issues/5644
Through the power of patience the x and y position for the `picoDeathConfirm` have been shifted. Also adds caching to `FunkinMemory` for the death sprite because Jackxson asked me to.
https://github.com/user-attachments/assets/bff74ea3-5354-4ac8-82bb-e680c0793ccf
> [BUGFIX] Fix the `pico-blazin` death sprite being offset and causing lag

- preload/data/characters/tankman-atlas.json
- preload/data/characters/tankman-bloody.json
For some reason, the names of Tankman's atlas and bloody variants are once again not named properly.
> [BUGFIX] Fix the Tankman variants using the same name

- preload/data/characters/spooky-dark.json
This PR fixes the frame indice set for 'spooky-dark' being off by one frame, as #159 did only for the normal variant.
The issue only affects 'danceLeft' and 'danceRight' for this character.
Fixes https://github.com/FunkinCrew/Funkin/issues/5541
> [BUGFIX] Sync idle animation for 'spooky-dark' with regular idle

- preload/data/characters/dad.json
- shared/images/characters/daddyDearest.xml
Fixes [FunkinCrew/Funkin#4377](https://github.com/FunkinCrew/Funkin/issues/4377); should ideally be paired with a fix for [FunkinCrew/Funkin#4380](https://github.com/FunkinCrew/Funkin/issues/4380)
* Removes two frames from the start of Daddy Dearest's idle animation and adds three to the end to fix its timing
* Adds two additional frames to his "idle-hold" animation so that his eyes animate properly
> Fix Daddy Dearest's idle animation

- preload/scripts/stages/phillyTrain.hxc
- preload/scripts/stages/phillyTrainErect.hxc
Fixes the bug caused by @sector-a's PR that causes the train to never appear after beating any week 3 song once. Makes sure to re-enable the train whenever the stage builds.
> [BUGFIX] Fix Week 3 train never appearing again after beating a Week 3 song

- preload/scripts/stages/spookyMansion.hxc
Lightning variables weren't properly reset at the start of every song in story mode, causing the first lightning strike to be delayed quite far into the level. This is most noticeable on Monster because the first lightning strike only plays near the end of the song, making it seem like lightning isn't happening at all. The lightning starts playing at normal intervals again after the first lightning strike, so I just had to add this check to make sure the first lightning strike played near the beginning of the song.
https://github.com/user-attachments/assets/ae539a64-655d-4101-8a1a-417918e9e592
> [BUGFIX] Fix Lightning Rarely Appearing in South and Monster in Story Mode

- preload/data/notestyles/funkin.json
[#FunkinCrew/Funkin3105](https://github.com/FunkinCrew/Funkin/issues/3105)
[#FunkinCrew/Funkin3427](https://github.com/FunkinCrew/Funkin/issues/3427)
This PR centers the note splashes, as they were a little bit off centered. I will make tiny adjustments to this if needed. People can give feedback for this PR.
> [ENHANCEMENT] Manually Offset Splashes

- preload/data/players/pico.json
This? https://github.com/FunkinCrew/Funkin/pull/5852
(idk, I was working on both at the same time)
None yet!
Freeplay Pico's y Positioning didn't match Freeplay BF's, so I gave it a little nudge for all the animations to fix it
https://github.com/user-attachments/assets/dcd4b401-0ad4-4fa5-b130-48330244b89d
> `[feat/flixel-animate]` Nudge Freeplay Pico's y Position to be consistent with Freeplay BF

- preload/data/ui/animation-editor/offset-editor-view.xml
FunkinCrew/Funkin#5974
Closes FunkinCrew/Funkin#5931
This PR changes the labels for the saving shortcuts in the Animation Editor to the new ones. See PR in the main repo for the reasoning for the new shortcuts.
The new shortcut labels displayed in the dialog:
> [ENHANCEMENT] Change Animation Editor save shortcuts (funkin.assets)

- exclude/data/ui/chart-editor/components/menubar.xml
Move menubar a little for new debugDisplay
> [BUGFIX] Move Chart Editor menu bar based on debug display

- exclude/data/ui/chart-editor/toolboxes/metadata.xml
[Funkin/#4770](https://github.com/FunkinCrew/Funkin/pull/4770)
Expands the selection of Time Signatures to two separate dropdowns and adds a dropdown for Time Changes.
Other changes:
- BPM stepper now allows for 3 decimals instead of just 1.
- The metadata window width is doubled in order to have enough space.
> Expanded Time Signatures & Time Changes in-editor.

- preload/data/stages/phillyTrain.json
https://github.com/FunkinCrew/Funkin/issues/6073
Very little offsets fix to the inconsistency between `phillyTrain` and `phillyTrainErect` (The game was unplayable without this fix).
The offsets now are based on `phillyTrainErect`.
Fix:
https://github.com/user-attachments/assets/5a116050-c05c-42c9-a242-56585f8db235
Funny Pico's hand (I didn't take the screenshot at the same frame)
> [ENHANCEMENT] Adjust offsets for BF in `phillyTrain` to match `phillyTrainErect`
